### ISSUE TITLE
Cannot find python2 for env

### ISSUE THREAD

**Issue by burnettzhong** [hoxu/gitstats#62]
I try to run gitstats with Python 2.7.1 installed, however it says:
`env: python2: No such file or directory`

**Comment by ari3s** [comment]
Pull request #61 should solve this issue (as well as Python 2 vs Python 3 compatibility).

**Comment by CheneyZJ** [comment]
I pull #61 ,still show the same error..(env: python2: No such file or directory)

**Comment by xuanskyer** [comment]
@burnettzhong  you can create a soft link for python2 like this:
`ln -s /usr/bin/python python2`
